[package]
name = "cosmic-initial-setup"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"

[dependencies]
env_logger = "0.10"
geonames = { path = "geonames" }
lazy_static = "1"
log = "0.4"
regex = "1"
tokio = { version = "1", features = ["sync"] }
# Internationalization
i18n-embed = { version = "0.13", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.6"
rust-embed = "6"
icu_collator = "1.5"
icu_provider = { version = "1.5", features = ["sync"] }

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = ["tokio", "winit"]

[features]
default = ["a11y", "wgpu"]
a11y = ["libcosmic/a11y"]
wgpu = ["libcosmic/wgpu"]

[profile.release-with-debug]
inherits = "release"
debug = true

[workspace]
members = ["geonames"]

# [patch.'https://github.com/pop-os/libcosmic.git']
# libcosmic = { path = "../libcosmic" }
# cosmic-config = { path = "../libcosmic/cosmic-config" }
# cosmic-theme = { path = "../libcosmic/cosmic-theme" }
